version: 2.1
working_directory: ~/client
orbs:
  react: thefrontside/react@0.2.0
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
